In [18]:
import numpy as np
from sklearn.linear_model import LogisticRegression
import pandas as pd
from sklearn.model_selection import cross_val_score
from sklearn.metrics import precision_recall_fscore_support
from sklearn.metrics import confusion_matrix
from matplotlib import pyplot as plt
from prettytable import PrettyTable


In [19]:
df = pd.read_csv('winequality-red.csv', delimiter=';')

In [20]:
output = df['quality']

In [21]:
inp = df.drop('quality', axis=1)

In [22]:
X = inp.values
y = output.values

In [23]:
def my_custom_score(estimator, X, y):
    global avg_numpy, fold_num
    table = PrettyTable(['Label', 'Precision', 'Recall', 'Fscore'])
    y_pred = estimator.predict(X)
    scores =  precision_recall_fscore_support(y, y_pred, average=None, warn_for=())
    
    avg_numpy = np.add(scores, avg_numpy)
    
    precision_per_class = scores[0].tolist()
    recall_per_class = scores[1].tolist()
    fscore_per_class = scores[2].tolist()
    
    print("Fold number {0}".format(fold_num+1))
    fold_num += 1
    for label in range(6):
        table.add_row([label+3, precision_per_class[label], recall_per_class[label], fscore_per_class[label]])
    print(table)
    print('\nConfusion Matrix\n{0}\n************************************\n'.format(confusion_matrix(y, y_pred, labels=[3,4,5,6,7,8])))
    print("\n\n")
    return 1

In [24]:
model = LogisticRegression()
avg_numpy = np.zeros((4, len(set(y.tolist()))))
fold_num = 0
scores = cross_val_score(model, X, y, scoring= my_custom_score, cv=5)
avg_numpy = np.divide(avg_numpy,5)

Fold number 1
+-------+--------------------+--------------------+---------------------+
| Label |     Precision      |       Recall       |        Fscore       |
+-------+--------------------+--------------------+---------------------+
|   3   |        0.0         |        0.0         |         0.0         |
|   4   |        0.0         |        0.0         |         0.0         |
|   5   | 0.5511111111111111 | 0.9051094890510949 |  0.6850828729281768 |
|   6   | 0.5217391304347826 |       0.375        | 0.43636363636363634 |
|   7   |        0.6         |       0.075        | 0.13333333333333333 |
|   8   |        0.0         |        0.0         |         0.0         |
+-------+--------------------+--------------------+---------------------+

Confusion Matrix
[[  0   0   2   0   0   0]
 [  0   0   8   3   0   0]
 [  0   0 124  13   0   0]
 [  0   0  80  48   0   0]
 [  0   0  11  26   3   0]
 [  0   0   0   2   2   0]]
************************************




Fold number 2
+-------+-

In [25]:
table = PrettyTable(['Labels', 'Avg_Precision', 'Avg_Recall', 'Avg_Fscore'])


In [26]:
for label in range(6):
    table.add_row([label + 3, avg_numpy[0][label], avg_numpy[1][label], avg_numpy[2][label]])
print(table)

+--------+----------------+----------------+----------------+
| Labels | Avg_Precision  |   Avg_Recall   |   Avg_Fscore   |
+--------+----------------+----------------+----------------+
|   3    |      0.0       |      0.0       |      0.0       |
|   4    |      0.0       |      0.0       |      0.0       |
|   5    | 0.64709820335  | 0.742786603693 | 0.682243128808 |
|   6    | 0.514908572706 | 0.611835629921 | 0.549550217771 |
|   7    | 0.361353383459 |     0.095      | 0.144079077552 |
|   8    |      0.0       |      0.0       |      0.0       |
+--------+----------------+----------------+----------------+
