In [1]:
import numpy as np
from sklearn.linear_model import LogisticRegression
import pandas as pd
from sklearn.model_selection import cross_val_score
from sklearn.metrics import precision_recall_fscore_support
from sklearn.metrics import confusion_matrix
from matplotlib import pyplot as plt

In [2]:
df = pd.read_csv('winequality-red.csv', delimiter=';')

In [3]:
print(list(df))

['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol', 'quality']


In [4]:
output = df['quality']

In [5]:
inp = df.drop('quality', axis=1)

In [6]:
X = inp.values
y = output.values

In [10]:
model = LogisticRegression()

In [11]:
def my_custom_score(estimator, X, y):
    y_pred = estimator.predict(X)
    scores =  precision_recall_fscore_support(y, y_pred, average=None)
    print("precision per class: %s" %(str(scores[0].tolist())))
    print("recall per class: %s" %(str(scores[1].tolist())))
    print("fscore per class: %s" %(str(scores[2].tolist())))
    print("****************")
    return 1

In [12]:
model = LogisticRegression()
scores = cross_val_score(model, X, y, scoring= my_custom_score, cv=5)

precision per class: [0.0, 0.0, 0.5511111111111111, 0.5217391304347826, 0.6, 0.0]
recall per class: [0.0, 0.0, 0.9051094890510949, 0.375, 0.075, 0.0]
fscore per class: [0.0, 0.0, 0.6850828729281768, 0.43636363636363634, 0.13333333333333333, 0.0]
****************
precision per class: [0.0, 0.0, 0.5813953488372093, 0.46923076923076923, 0.42105263157894735, 0.0]
recall per class: [0.0, 0.0, 0.7352941176470589, 0.4765625, 0.2, 0.0]
fscore per class: [0.0, 0.0, 0.6493506493506493, 0.4728682170542636, 0.2711864406779661, 0.0]
****************
precision per class: [0.0, 0.0, 0.6748466257668712, 0.5364238410596026, 0.2857142857142857, 0.0]
recall per class: [0.0, 0.0, 0.8088235294117647, 0.6328125, 0.05, 0.0]
fscore per class: [0.0, 0.0, 0.7357859531772575, 0.5806451612903226, 0.0851063829787234, 0.0]
****************
precision per class: [0.0, 0.0, 0.7241379310344828, 0.5263157894736842, 0.5, 0.0]
recall per class: [0.0, 0.0, 0.6176470588235294, 0.7874015748031497, 0.15, 0.0]
fscore per class

C:\Users\ragha\Miniconda3\envs\for_ml\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\ragha\Miniconda3\envs\for_ml\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\ragha\Miniconda3\envs\for_ml\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\ragha\Miniconda3\envs\for_ml\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samp

In [21]:
print(set(y.tolist()))

{3, 4, 5, 6, 7, 8}


In [22]:
model = LogisticRegression()
model.fit(X, y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [23]:
y_pred = model.predict(X)

In [24]:
print(confusion_matrix(y, y_pred, labels=[3,4,5,6,7,8]))

[[  0   0   9   1   0   0]
 [  0   0  37  15   1   0]
 [  0   0 519 160   2   0]
 [  0   0 232 397   9   0]
 [  0   0  13 169  17   0]
 [  0   0   0  13   5   0]]
